### ISSUE TITLE
Relais d'avertissement avant le passage au Core 2025.1

### ISSUE THREAD

**Issue by Bzh972** [Doubledom45/TEST-RFPLAYER#5]
Salut,

bon je sais y'a encore le temps et c'est peut-être déjà en cours de traitement mais pour une fois que je remets mon nez dans les logs et que je comprends ce qu'il me dit, je transmets l'info ;)

Si tu veux que je fasses des tests ou autres n'hésite pas !

Enregistreur: homeassistant.components.cover
Source: helpers/deprecation.py:205
intégration: Volets (documentation, problèmes)
S'est produit pour la première fois: 11:28:31 (12 occurrences)
Dernier enregistrement: 11:28:31

DEVICE_CLASS_SHUTTER was used from rfplayer, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverDeviceClass.SHUTTER instead, please create a bug report at https://github.com/Doubledom45/TEST-RFPLAYER/issues
SUPPORT_OPEN was used from rfplayer, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.OPEN instead, please create a bug report at https://github.com/Doubledom45/TEST-RFPLAYER/issues
SUPPORT_CLOSE was used from rfplayer, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.CLOSE instead, please create a bug report at https://github.com/Doubledom45/TEST-RFPLAYER/issues
SUPPORT_SET_POSITION was used from rfplayer, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.SET_POSITION instead, please create a bug report at https://github.com/Doubledom45/TEST-RFPLAYER/issues
SUPPORT_STOP was used from rfplayer, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.STOP instead, please create a bug report at https://github.com/Doubledom45/TEST-RFPLAYER/issues

**Comment by Doubledom45** [comment]
Salut je crois que j'ai modifier sur la version ! dis mois laquelle tu as!
## Depuis HACS
![image](https://github.com/Doubledom45/TEST-RFPLAYER/assets/97252459/ea30066e-501c-4d54-9b28-a9bc3ac15638)
## Sur le Github
![image](https://github.com/Doubledom45/TEST-RFPLAYER/assets/97252459/a4356e75-8f86-4177-b9b0-bcd5b9fb5f7c)

**Comment by Bzh972** [comment]
la toute dernière depuis hacs en récupérant le dépôt sur github, téléchargée et installée 3 minutes avant le log 
![image](https://github.com/Doubledom45/TEST-RFPLAYER/assets/23426560/f355b8a2-e16d-46fe-b810-baac15dc48e5)
