### ISSUE TITLE
Enhancement: short packet name not user friendly as default entity name

### ISSUE THREAD

**Issue by racletteparty** [Doubledom45/TEST-RFPLAYER#8]
Thanks for the great work to make the integration as exhaustive as possible.

I'm just wondering why using a short packet field name to build the entity name.
temperature is easier to read than tmp. same hygrometry and hyg.

I'd suggest to use a full name to build the entity name rather than the shortened one.

**Comment by Doubledom45** [comment]
Salut.
Les noms long sont trop problématique sur l'affichage dans appareils , ( cela exister avant), mais comme il est facile de renommer dans les entités du RFPLAYER, pour un nom plus conviviable, j'ai préférer faire des abréviations !
